<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --tables=activities,activity_files,activity_participants,attributes,attribute_options,attribute_values,core_config,countries,country_states,email_attachments,email_templates,emails,groups,lead_pipeline_stages,lead_pipelines,lead_products,lead_sources,lead_stages,leads,organizations,persons,products,quote_items,quotes,roles,tags,workflows
         *
         */

        DB::table("attributes")->truncate();

        $dataTables = [
            [
                'id' => 1,
                'code' => 'title',
                'name' => 'Title',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'leads',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 2,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'leads',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 3,
                'code' => 'lead_value',
                'name' => 'Lead Value',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'leads',
                'sort_order' => 3,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 4,
                'code' => 'lead_source_id',
                'name' => 'Source',
                'type' => 'select',
                'lookup_type' => 'lead_sources',
                'entity_type' => 'leads',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 5,
                'code' => 'lead_type_id',
                'name' => 'Type',
                'type' => 'select',
                'lookup_type' => 'lead_types',
                'entity_type' => 'leads',
                'sort_order' => 5,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 6,
                'code' => 'user_id',
                'name' => 'Sales Owner',
                'type' => 'select',
                'lookup_type' => 'users',
                'entity_type' => 'leads',
                'sort_order' => 7,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 7,
                'code' => 'expected_close_date',
                'name' => 'Expected Close Date',
                'type' => 'date',
                'lookup_type' => NULL,
                'entity_type' => 'leads',
                'sort_order' => 8,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 8,
                'code' => 'lead_pipeline_id',
                'name' => 'Pipeline',
                'type' => 'lookup',
                'lookup_type' => 'lead_pipelines',
                'entity_type' => 'leads',
                'sort_order' => 9,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 9,
                'code' => 'lead_pipeline_stage_id',
                'name' => 'Stage',
                'type' => 'lookup',
                'lookup_type' => 'lead_pipeline_stages',
                'entity_type' => 'leads',
                'sort_order' => 10,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 10,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 11,
                'code' => 'emails',
                'name' => 'Emails',
                'type' => 'email',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 12,
                'code' => 'contact_numbers',
                'name' => 'Contact Numbers',
                'type' => 'phone',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 3,
                'validation' => 'numeric',
                'is_required' => 0,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 13,
                'code' => 'job_title',
                'name' => 'Job Title',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 14,
                'code' => 'user_id',
                'name' => 'Sales Owner',
                'type' => 'lookup',
                'lookup_type' => 'users',
                'entity_type' => 'persons',
                'sort_order' => 5,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 15,
                'code' => 'organization_id',
                'name' => 'Organization',
                'type' => 'lookup',
                'lookup_type' => 'organizations',
                'entity_type' => 'persons',
                'sort_order' => 6,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 16,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'organizations',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 17,
                'code' => 'address',
                'name' => 'Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'organizations',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 18,
                'code' => 'user_id',
                'name' => 'Sales Owner',
                'type' => 'lookup',
                'lookup_type' => 'users',
                'entity_type' => 'organizations',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 19,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 20,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 21,
                'code' => 'sku',
                'name' => 'SKU',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 22,
                'code' => 'quantity',
                'name' => 'Quantity',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 4,
                'validation' => 'numeric',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 23,
                'code' => 'price',
                'name' => 'Price',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 5,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 24,
                'code' => 'user_id',
                'name' => 'Sales Owner',
                'type' => 'select',
                'lookup_type' => 'users',
                'entity_type' => 'quotes',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 25,
                'code' => 'subject',
                'name' => 'Subject',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 26,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 27,
                'code' => 'billing_address',
                'name' => 'Billing Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 28,
                'code' => 'shipping_address',
                'name' => 'Shipping Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 5,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 29,
                'code' => 'discount_percent',
                'name' => 'Discount Percent',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 6,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 30,
                'code' => 'discount_amount',
                'name' => 'Discount Amount',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 7,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 31,
                'code' => 'tax_amount',
                'name' => 'Tax Amount',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 8,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 32,
                'code' => 'adjustment_amount',
                'name' => 'Adjustment Amount',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 9,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 33,
                'code' => 'sub_total',
                'name' => 'Sub Total',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 10,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 34,
                'code' => 'grand_total',
                'name' => 'Grand Total',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 11,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 35,
                'code' => 'expired_at',
                'name' => 'Expired At',
                'type' => 'date',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 12,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 36,
                'code' => 'person_id',
                'name' => 'Person',
                'type' => 'lookup',
                'lookup_type' => 'persons',
                'entity_type' => 'quotes',
                'sort_order' => 13,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 37,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 38,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 39,
                'code' => 'contact_name',
                'name' => 'Contact Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 40,
                'code' => 'contact_emails',
                'name' => 'Contact Emails',
                'type' => 'email',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 41,
                'code' => 'contact_numbers',
                'name' => 'Contact Numbers',
                'type' => 'phone',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 5,
                'validation' => 'numeric',
                'is_required' => 0,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ],
            [
                'id' => 42,
                'code' => 'contact_address',
                'name' => 'Contact Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 6,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2025-11-15 07:31:30',
                'updated_at' => '2025-11-15 07:31:30',
            ]
        ];
        
        DB::table("attributes")->insert($dataTables);
    }
}